[package]
name = "chip-eight"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
ctrlc = "3.4.6"
rand = "0.9.0"
sdl3 = { version = "0.14.22", features = ["build-from-source"] }
